version: "3.9"
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "YourOrg"
      LDAP_DOMAIN: "yourorg.local"
      LDAP_ADMIN_PASSWORD: "strongldapadminpassword"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    networks:
      - internal

  samba-ad:
    image: dperson/samba-ad:latest
    container_name: samba-ad
    environment:
      SAMBA_DOMAIN: "YOURDOMAIN"
      SAMBA_ADMIN_PASSWORD: "strongadadminpassword"
      SAMBA_HOSTNAME: "adserver"
    ports:
      - "445:445"
      - "138:138"
      - "139:139"
      - "389:389"
      - "636:636"
      - "3268:3268"
      - "3269:3269"
      - "53:53/udp"
      - "53:53/tcp"
      - "88:88"
      - "135:135"
      - "464:464"
      - "49152-65535:49152-65535"
    volumes:
      - samba-ad-data:/var/lib/samba
    networks:
      - internal

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ldap
      - samba-ad
    networks:
      - internal
      - vpc

volumes:
  ldap-data:
  ldap-config:
  samba-ad-data:

networks:
  internal:
    driver: bridge
  vpc:
    driver: bridge